# Generated by Django 4.2.16 on 2024-09-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_employee_alter_organizationresponsible_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='service_type',
            field=models.CharField(choices=[('CONSULTING', 'Consulting'), ('CONSTRUCTION', 'Construction'), ('SUPPLY', 'Supply'), ('IT', 'IT Services')], default='CONSULTING', max_length=20),
        ),
    ]
