# Generated by Django 4.2.16 on 2024-09-11 16:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], max_length=10)),
                ('service_type', models.CharField(choices=[('CONSULTING', 'Consulting'), ('CONSTRUCTION', 'Construction'), ('SUPPLY', 'Supply'), ('IT', 'IT Services')], max_length=20)),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tenders.tender')),
            ],
        ),
    ]
